### ISSUE TITLE
Package page has broken link to build results

### ISSUE THREAD

**Issue by rillig** [bsiegert/BulkTracker#43]
https://releng.netbsd.org/bulktracker/pkgtools/pkglint

The links in the 'Package Name' column have the form:
> https://releng.netbsd.org/pkg/1507506

This form is missing the `/bulktracker`. Same for the 'Build Timestamp' column.

**Comment by bsiegert** [comment]
Thanks!

I had made that change already but somehow it got lost in a merge :(
