### ISSUE TITLE
Link from bulk build page to original report

### ISSUE THREAD

**Issue by riastradh** [bsiegert/BulkTracker#52]
Sometimes there is more information in the machine-readable bulk report than bulktracker shows.  How do I get back to the original machine-readable bulk report, or at least back to the mail-index page referencing it, from a bulk build page like https://releng.netbsd.org/bulktracker/build/645?

(I don't remember offhand whether bulktracker scrapes the page or reads the machine-readable report, but either way it would be nice to get a link to the machine-readable report.)

**Comment by bsiegert** [comment]
It scrapes the machine-readable report. The URL is in the database, so we can just show it.
