### ISSUE TITLE
Missing makefile to regen ddao/queries.sql.go

### ISSUE THREAD

**Issue by riastradh** [bsiegert/BulkTracker#68]
How do I regenerate this when I've changed queries.sql?

I tried installing databases/sqlc from pkgsrc, but it fails:

```
ddao/manual_additions.go:157:9: cannot use d.getAllPkgsMatching(ctx, "%" + substr + "%") (value of type []interface{}) as []string value in return statement
```

It appears to be somewhat out-of-date.

**Comment by bsiegert** [comment]
You will need to run `sqlc generate` with wip/sqlc. However, IIRC, I couldn't get that version to compile on NetBSD because it depends on some WebAssembly thing that is missing NetBSD support :(

**Comment by bsiegert** [comment]
I updated https://pkgsrc.se/databases/sqlc to 1.26.0, so this should work now. Thanks for the feedback.
