### ISSUE TITLE
highlight bulk-test failures somehow

### ISSUE THREAD

**Issue by gdt** [bsiegert/BulkTracker#71]
We have bulk-test-foo for various foo, and they are meant to be sentinels.    I'm not sure what's best, but perhaps a section before the packages breaking the most others which is just a list of bulk-test-foo that fail together with the first few actual failures in their depdendency tree, as in:
```
bulk-test-erlang: erlang-jose
bulk-test-php: php81-pgsql php80-pgsql
```

This should be relatively unobtrusive, compared to usefulness.

**Comment by bsiegert** [comment]
Sneak preview:

![grafik](https://github.com/user-attachments/assets/473446b2-b675-4e85-a187-af00f184dc9e)

Still working on turning the failed dependencies into links.

**Comment by bsiegert** [comment]
This will be in the next version!
